
---
- name: Add GNS3 repository
  ansible.builtin.apt_repository:
    repo: ppa:gns3/ppa
  become: true

- name: Add GNS3 unstable repository
  ansible.builtin.apt_repository:
    repo: ppa:gns3/unstable
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install GNS3 package
  ansible.builtin.package:
    name:
      - gns3-gui
      - gns3-server
      - gns3-webclient-pack
    state: latest
  become: true

- name: Add vagrant to ubridge group
  ansible.builtin.user:
    name: vagrant
    append: true
    groups:
      - ubridge
  become: true
