---
- name: install Desktop env
  ansible.builtin.package:
    name:
      - ubuntu-desktop
      - lightdm
    state: latest
  become: true

- name: Config Display manager
  ansible.builtin.shell: |
    spawn dpkg-reconfigure lightdm -f readline
    expect "Default display manager:"
    send "2\r"
    expect eof
    exit
  args:
    executable: /usr/bin/expect
  become: true
