---
- name: Setup & Configure Docker
  hosts: all
  connection: local
  tasks:
    - name: Add docker key to apt
      ansible.builtin.apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/trusted.gpg.d/docker.gpg
        state: present
      become: true

    - name: Configure docker repository
      ansible.builtin.apt_repository:
        filename: docker
        repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts.lsb.codename }} stable
        update_cache: true
      become: true

    - name: Install Docker package
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
      become: true

    - name: Add vagrant to docker group
      ansible.builtin.user:
        name: vagrant
        append: true
        groups:
          - docker
      become: true
