---
- name: Setup & Configure GNS3
  hosts: all
  connection: local
  handlers:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true

  tasks:
    - name: Add GNS3 repository
      ansible.builtin.apt_repository:
        repo: ppa:gns3/ppa
      notify: Update apt cache
      become: true

    - name: Flush handler if we need to update apt cache before install
      ansible.builtin.meta: flush_handlers

    - name: Install GNS3 package
      ansible.builtin.package:
        name:
          - gns3-gui
          - gns3-server
        state: latest
      become: true

    - name: Add vagrant to ubridge group
      ansible.builtin.user:
        name: vagrant
        append: true
        groups:
          - ubridge
      become: true
