---
- name: Setup & Configure Desktop env
  hosts: all
  connection: local
  tasks:
    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg
        mode: 0o600

    - name: Extract Docker GPG key
      ansible.builtin.command: >
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg
      become: true

    - name: Configure docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch={{ ansible_facts.architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts.lsb.codename }} stable
        update_cache: true
      become: true

    - name: Install Docker package
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
      become: true

    - name: Add vagrant to docker group
      ansible.builtin.user:
        name: vagrant
        append: true
        groups:
          - docker
      become: true
