---
- name: Basic configuration
  hosts: all
  connection: local
  tasks:
    - name: Install basic packages
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - wget
          - gnupg
          - lsb-release
          - software-properties-common
          - git
          - vim
        state: latest
      become: true

    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg
        mode: 0o600

    - name: Extract Docker GPG key
      ansible.builtin.command: >
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg
      become: true

    - name: Configure docker repository
      ansible.builtin.shell: |
        set -o pipefail
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
          | sudo tee /etc/apt/sources.list.d/docker.list
      args:
        creates: /etc/apt/sources.list.d/docker.list
        executable: /bin/bash
      become: true

    - name: Add GNS3 repository
      ansible.builtin.apt_repository:
        repo: ppa:gns3/ppa
      become: true

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Install docker + GNS3 + netutils
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin

          - gns3-gui
          - gns3-server

          - dnsutils
          - wireshark
        state: latest
      become: true

    - name: Add vagrant to docker group
      ansible.builtin.user:
        name: vagrant
        append: true
        groups:
          - docker
      become: true
