---
- name: Basic configuration
  hosts: all
  connection: local
  tasks:
    - name: Install basic packages
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - wget
          - gnupg
          - lsb-release
          - software-properties-common
          - git
          - vim
          - expect
        state: latest
      become: true

    - ansible.builtin.import_tasks: config_docker_repo.yml
    - ansible.builtin.import_tasks: config_gns3_repo.yml

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Install docker + GNS3 + netutils
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin

          - dnsutils
          - wireshark
        state: latest
      become: true

    - name: Add vagrant to docker group
      ansible.builtin.user:
        name: vagrant
        append: true
        groups:
          - docker
      become: true

    - ansible.builtin.import_tasks: setup_desktop_env.yml
