---
- name: Basic configuration
  hosts: all
  connection: local
  tasks:
    - name: Install basic packages
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - wget
          - gnupg
          - lsb-release
          - software-properties-common
          - git
          - vim
          - expect
        state: latest
      become: true

    - ansible.builtin.import_tasks: config_docker_repo.yml
    - ansible.builtin.import_playbook: config_gns3_repo.yml

    - name: Install netutils
      ansible.builtin.package:
        name:
          - dnsutils
          - wireshark
        state: latest
      become: true

    - ansible.builtin.import_playbook: setup_desktop_env.yml
